venue_categories = {
    'Monuments': [
        'Arcades',
        'Architectural Tours',
        'Buddhist Temples',
        'Castles',
        'Churches',
        'Hindu Temples',
        'Landmarks & Historical Buildings',
        'Mosques',
        'Public Plazas',
        'Synagogues',
        'Town Hall'
    ],
    'Museums & art galleries': [
        'Art Schools',
        'Playgrounds',
        'Painters',
        'Amusement Parks',
        'Arts & Crafts',
        'Museums',
        'Art Galleries',
        'Antiques',
        'Food Tours',
        'Seafood Markets',
        'Tours',
        'Art Museums',
        'Art Restoration',
        'Art Tours',
        'Beer Tours',
        'Boat Tours',
        'Botanical Gardens',
        'Caricatures',
        'Children\'s Museums',
        'Christmas Markets',
        'Commissioned Artists',
        'Community Gardens',
        'Cultural Center',
        'Haunted Houses',
        'Historical Tours',
        'Marinas',
        'Planetarium',
        'Public Art',
        'Street Art',
        'Walking Tours',
        'Water Parks',
        'Wedding Chapels',
        'Wine Tours',
        'Zoos',
        'Lakes',
        'Beaches',
        'Parks',
        'Libraries',
        'Video/Film Production'
    ],
    'Cinemas & concert & theatres': [
        'Arts & Entertainment',
        'Escape Games',
        'Comedy Clubs',
        'Music Venues',
        'Festivals',
        'Recreation Centers',
        'Performing Arts',
        'Social Clubs',
        'Cinema',
        'Venues & Event Spaces',
        'Jazz & Blues',
        'Choirs',
        'General Festivals',
        'Horse Racing',
        'Mini Golf',
        'Petting Zoos',
        'Drive-In Theater',
        'Dinner Theater',
        'Outdoor Movies',
        'Fun Fair',
        'Karaoke',
        'Country Dance Halls',
        'Bingo Halls',
        'Musicians',
        'Opera & Ballet',
        'Pool & Billiards',
        'Bowling',
        'Cabaret'
    ],
    'Nightclubs & bars': [
        'Bars',
        'Pubs',
        'Cocktail Bars',
        'Dive Bars',
        'Nightlife',
        'Adult Entertainment',
        'Sports Bars',
        'Strip Clubs',
        'Adult',
        'Tiki Bars',
        'Piano Bars',
        'Brewpubs',
        'Beer Bar',
        'Cannabis Collective',
        'Beer Hall',
        'Whiskey Bars',
        'Striptease Dancers',
        'Bartenders',
        'DJs',
        'Bar Crawl',
        'Club Crawl',
        'Erotic Massage',
        'Irish Pub',
        'Pool Halls',
        'Gay Bars',
        'Cannabis Tours',
        'Casinos',
        'Island Pub',
        'Beer',
        'Country Clubs',
        'Dance Clubs',
        'Wine & Spirits',
        'Cannabis Dispensaries'
    ],
    'Cafés & restaurants': [
        'Burgers',
        'Ice Cream & Frozen Yogurt',
        'Breakfast & Brunch',
        'Bagels',
        'Restaurants',
        'Bakeries',
        'Sandwiches',
        'Tea Rooms',
        'Salad',
        'Coffee & Tea',
        'Soup',
        'Specialty Food',
        'Ethnic Food',
        'Wine Bars',
        'Food Court',
        'Wraps',
        'Tapas/Small Plates',
        'Donuts',
        'Imported Food',
        'Cafes',
        'Tacos',
        'Chicken Wings',
        'Food Trucks',
        'Pizza',
        'Seafood',
        'Barbeque',
        'Buffets',
        'Desserts',
        'Sushi Bars',
        'Gastropubs',
        'Diners',
        'Izakaya',
        'Comfort Food',
        'Fast Food',
        'Creperies',
        'Sugar Shacks',
        'Ramen',
        'Juice Bars & Smoothies',
        'Delis',
        'Bubble Tea',
        'Hot Dogs',
        'Dim Sum',
        'Noodles',
        'Candy Stores',
        'Steakhouses',
        'Cupcakes',
        'Custom Cakes',
        'Fish & Chips',
        'Poutineries',
        'Tapas Bars',
        'Live/Raw Food',
        'Cheesesteaks',
        'Wineries',
        'Breweries',
        'Food Stands',
        'Personal Chefs',
        'Coffee Roasteries',
        'Curry Sausage',
        'Do-It-Yourself Food',
        'Distilleries',
        'Brasseries',
        'Patisserie/Cake Shop',
        'Macarons',
        'Bistros',
        'Kebab',
        'Scavenger Hunts',
        'Beach Bars',
        'Beer Garden',
        'Fondue',
        'Hot Pot',
        'Soul Food',
        'Hookah Bars',
        'Milkshake Bars',
        'Falafel',
        'Gelato',
        'Pretzels',
        'Beer Gardens',
        'Waffles',
        'Wine Tasting Room',
        'Mobile Home Parks',
        'Teppanyaki',
        'New Mexican Cuisine',
        'Pita',
        'Cafeteria',
        'Acai Bowls',
        'Champagne Bars',
        'Swiss Food',
        'Japanese Curry',
        'Coffeeshops',
        'Udon',
        'Pop-Up Restaurants',
        'Cideries',
        'Signature Cuisine',
        'Shaved Snow',
        'Tempura',
        'Tonkatsu',
        'Empanadas',
        'Supper Clubs',
        'Conveyor Belt Sushi',
        'Pub Food',
        'Themed Cafes',
        'Baguettes',
        'Hotel bar',
        'Wok',
        'Parent Cafes',
        'Hong Kong Style Cafe',
        'Drive-Thru Bars',
        'Schnitzel',
        'Mulled Wine',
        'Flatbread',
        'Friterie',
        'Churros',
        'Game Meat',
        'Rotisserie Chicken',
        'Soba'
    ],
    'Shops & consumptive activies': [
        'Blow Dry/Out Services',
        'Hair Stylists',
        'Men\'s Hair Salons',
        'Shopping',
        'Beauty & Spas',
        'Sporting Goods',
        'Hair Extensions',
        'Barbers',
        'Books',
        'Hair Salons',
        'Mags',
        'Body Shops',
        'Tanning',
        'Wholesale Stores',
        'Fashion',
        'Tattoo',
        'Watch Repair',
        'Men\'s Clothing',
        'Eyelash Service',
        'Gyms',
        'Piercing',
        'Women\'s Clothing',
        'Jewelry Repair',
        'Spray Tanning',
        'Home & Garden',
        'Guns & Ammo',
        'Florists',
        'Furniture Stores',
        'Flowers & Gifts',
        'Music & DVDs',
        'Fitness & Instruction',
        'Jewelry',
        'Music & Video',
        'Lighting Fixtures & Equipment',
        'Massage',
        'Massage Therapy',
        'Skin Care',
        'Department Stores',
        'Discount Store',
        'Home Decor',
        'Drugstores',
        'Eyewear & Opticians',
        'Hobby Shops',
        'Office Equipment',
        'Chocolatiers & Shops',
        'Cosmetics & Beauty Supply',
        'Shoe Stores',
        'Accessories',
        'Formal Wear',
        'Sewing & Alterations',
        'Shoe Repair',
        'Motorcycle Dealers',
        'Internet Cafes',
        'Photography Stores & Services',
        'Plus Size Fashion',
        'Hair Removal',
        'Waxing',
        'Sports Wear',
        'Clothing Rental',
        'Uniforms',
        'Makeup Artists',
        'Permanent Makeup',
        'Nail Salons',
        'Shopping Centers',
        'Videos & Video Game Rental',
        'Bookstores',
        'Souvenir Shops',
        'Used Bookstore',
        'Gift Shops',
        'International Grocery',
        'Toy Stores',
        'Thrift Stores',
        'Ethical Grocery',
        'Comic Books',
        'Tabletop Games',
        'Mobile Phones',
        'Pet Stores',
        'Street Vendors',
        'Floral Designers',
        'Baby Gear & Furniture',
        'Farmers Market',
        'Hardware Stores',
        'Dog Parks',
        'Kids Activities',
        'Eyebrow Services',
        'Virtual Reality Centers',
        'Mobile Phone Accessories',
        'Outdoor Gear',
        'Bike Rentals',
        'Tattoo Removal',
        'Motorcycle Gear',
        'Clowns',
        'Face Painting',
        'Golf Equipment',
        'Beverage Store',
        'Nail Technicians',
        'Watches',
        'Video Game Stores',
        'Art Supplies',
        'Flea Markets',
        'Henna Artists',
        'Costumes',
        'Knitting Supplies',
        'Children\'s Clothing',
        'Maternity Wear',
        'Art Classes',
        'Paint & Sip',
        'Paint Stores',
        'Ski & Snowboard Shops',
        'Cheese Shops',
        'Piano Stores',
        'Vinyl Records',
        'Lingerie',
        'Personal Shopping',
        'Party Characters',
        'Herbs & Spices',
        'Outlet Stores',
        'Embroidery & Crochet',
        'Hunting & Fishing Supplies',
        'Spiritual Shop',
        'Leather Goods',
        'Fabric Stores',
        'Fur Clothing',
        'Leisure Centers',
        'Swimwear',
        'Tasting Classes',
        'Wine Tasting Classes',
        'Popcorn Shops',
        'Paint-Your-Own Pottery',
        'Fitness/Exercise Equipment',
        'Photo Booth Rentals',
        'Clock Repair',
        'Wigs',
        'Saunas',
        'Organic Stores',
        'Smokehouse',
        'Pop-up Shops',
        'Guitar Stores',
        'Candle Stores',
        'Magicians',
        'Pasta Shops',
        'Bespoke Clothing',
        'Ethnic Grocery',
        'Tanning Beds',
        'Skate Shops',
        'Surf Shop',
        'Body Contouring',
        'Reptile Shops',
        'Christmas Trees',
        'Golf Equipment Shops',
        'Oxygen Bars',
        'Carousels',
        'Party Bike Rentals',
        'Jet Skis',
        'Concept Shops',
        'Bird Shops',
        'Bike Shop',
        'Teeth Whitening',
        'Tableware',
        'Cigar Bars',
        'Horse Equipment Shops',
        'Perfume',
        'Public Markets',
        'Herbal Shops',
        'Market Stalls',
        'Playsets',
        'Day Spas'
    ],
    'Offices & work premises': [
        'Cosmetic Dentists',
        'Oral Surgeons',
        'Orthodontists',
        'Departments of Motor Vehicles',
        'Dentists',
        'Public Services & Government',
        'General Dentistry',
        'Home Services',
        'Property Management',
        'Health & Medical',
        'Real Estate',
        'TV Mounting',
        'Event Planning & Services',
        'Office Cleaning',
        'Nurseries & Gardening',
        'Home Cleaning',
        'Self Storage',
        'Car Rental',
        'Electricians',
        'Contractors',
        'Auto Glass Services',
        'Education',
        'Specialty Schools',
        'Pool Cleaners',
        'Auto Repair',
        'Smog Check Stations',
        'Window Washing',
        'Endodontists',
        'Carpet Cleaning',
        'Real Estate Services',
        'Pool & Hot Tub Service',
        'Automotive',
        'Auto Detailing',
        'Oil Change Stations',
        'Professional Services',
        'Home Automation',
        'Home Theatre Installation',
        'Television Service Providers',
        'Doctors',
        'Orthopedists',
        'Chiropractors',
        'Advertising',
        'Graphic Design',
        'Marketing',
        'Screen Printing',
        'Screen Printing/T-Shirt Printing',
        'Web Design',
        'Real Estate Agents',
        'Internal Medicine',
        'Optometrists',
        'Religious Organizations',
        'Dance Schools',
        'Dance Studios',
        'Pets',
        'Veterinarians',
        'Auto Parts & Supplies',
        'Physical Therapy',
        'Weight Loss Centers',
        'Pet Groomers',
        'Pet Services',
        'Pet Sitting',
        'Pet Training',
        'Countertop Installation',
        'Kitchen & Bath',
        'Tiling',
        'Appliances & Repair',
        'Flooring',
        'Head Shops',
        'Tobacco Shops',
        'Motorcycle Repair',
        'Counseling & Mental Health',
        'Bridal',
        'Wedding Planning',
        'Air Duct Cleaning',
        'Heating & Air Conditioning/HVAC',
        'Damage Restoration',
        'Grout Services',
        'Party & Event Planning',
        'Food Delivery Services',
        'Convenience Stores',
        'Grocery',
        'Nutritionists',
        'Pest Control',
        'Electronics Repair',
        'IT Services & Computer Repair',
        'Mobile Phone Repair',
        'Plumbing',
        'Health Markets',
        'Vape Shops',
        'Septic Services',
        'Musical Instruments & Teachers',
        'Refinishing Services',
        'Gas Stations',
        'Auto Upholstery',
        'Mobile Dent Repair',
        'Water Heater Installation/Repair',
        'Building Supplies',
        'Interior Design',
        'Shades & Blinds',
        'Landscape Architects',
        'Landscaping',
        'Financial Services',
        'Mortgage Brokers',
        'Mortgage Lenders',
        'Dog Walkers',
        'Carpet Installation',
        'Carpeting',
        'Child Care & Day Care',
        'Elementary Schools',
        'Preschools',
        'Notaries',
        'Printing Services',
        'Shipping Centers',
        'Accountants',
        'Tax Services',
        'Medical Centers',
        'Midwives',
        'Urgent Care',
        'Cannabis Clinics',
        'Pharmacy',
        'Walk-in Clinics',
        'Dry Cleaning & Laundry',
        'Laundry Services',
        'Movers',
        'Pediatric Dentists',
        'Medical Spas',
        'Pressure Washers',
        'Diagnostic Imaging',
        'Diagnostic Services',
        'Utilities',
        'Photographers',
        'Session Photography',
        'Solar Installation',
        'Reflexology',
        'Computers',
        'Electronics',
        'Car Stereo Installation',
        'Lawyers',
        'Personal Injury Law',
        'Career Counseling',
        'Employment Agencies',
        'Hot Tub & Pool',
        'Glass & Mirrors',
        'Windows Installation',
        'Windshield Installation & Repair',
        'Auto Customization',
        'Car Wash',
        'Artificial Turf',
        'Community Service/Non-Profit',
        'Door Sales/Installation',
        'Party Equipment Rentals',
        'Car Dealers',
        'Appliances',
        'Drywall Installation & Repair',
        'Handyman',
        'Hospitals',
        'Laundromat',
        'Post Offices',
        'Cardiologists',
        'Roadside Assistance',
        'Towing',
        'Party Supplies',
        'Internet Service Providers',
        'Appraisal Services',
        'Commercial Real Estate',
        'Acupuncture',
        'Life Coach',
        'Engraving',
        'Signmaking',
        'Mattresses',
        'Pet Transportation',
        'Fire Protection Services',
        'Security Systems',
        'Furniture Repair',
        'Furniture Reupholstery',
        'Cabinetry',
        'Fences & Gates',
        'Metal Fabricators',
        'Gutter Services',
        'Shutters',
        'Water Purification Services',
        'Waterproofing',
        'Auto Electric Services',
        'Pediatricians',
        'Used Car Dealers',
        'Bike Repair/Maintenance',
        'Shaved Ice',
        'Event Photography',
        'Transmission Repair',
        'CPR Classes',
        'First Aid Classes',
        'Banks & Credit Unions',
        'Surgeons',
        'Garage Door Services',
        'Fingerprinting',
        'Laboratory Testing',
        'Telecommunications',
        'Bail Bondsmen',
        'Cosmetic Surgeons',
        'Plastic Surgeons',
        'Dermatologists',
        'Laser Hair Removal',
        'Occupational Therapy',
        'RV Dealers',
        'RV Repair',
        'Wheel & Rim Repair',
        'Neurologist',
        'Sleep Specialists',
        'Spine Surgeons',
        'Talent Agencies',
        'Auto Loan Providers',
        'Check Cashing/Pay-day Loans',
        'Title Loans',
        'Preventive Medicine',
        'Real Estate Photography',
        'Videographers',
        'Roof Inspectors',
        'Roofing',
        'Siding',
        'Gardeners',
        'Tree Services',
        'Personal Assistants',
        'Keys & Locksmiths',
        'Boat Repair',
        'Payroll Services',
        'Home Network Installation',
        'Home Window Tinting',
        'Registration Services',
        'Battery Stores',
        'Vocational & Technical School',
        'Blood & Plasma Donation Centers',
        'Currency Exchange',
        'Public Relations',
        'Naturopathic/Holistic',
        'Middle Schools & High Schools',
        'Divorce & Family Law',
        'Psychiatrists',
        'Childbirth Education',
        'Lactation Services',
        'Car Window Tinting',
        'Doulas',
        'Recycling Center',
        'Meat Shops',
        'Farms',
        'Commercial Truck Repair',
        'Truck Rental',
        'Home Inspectors',
        'Data Recovery',
        'Community Centers',
        'Pain Management',
        'Audiologist',
        'Hearing Aid Providers',
        'Installment Loans',
        'Home Inspectors',
        'Shared Office Spaces',
        'Cards & Stationery',
        'Ophthalmologists',
        'Radiologists',
        'Private Tutors',
        'Couriers & Delivery Services',
        'Junk Removal & Hauling',
        'Packing Services',
        'Laser Eye Surgery/Lasik',
        'Bankruptcy Law',
        'Packing Supplies',
        'Periodontists',
        'Irrigation',
        'Auto Insurance',
        'Home & Rental Insurance',
        'Insurance',
        'ATV Rentals/Tours',
        'Motorcycle Rental',
        'Sports Medicine',
        'Reiki',
        'Musical Instrument Services',
        'Firearm Training',
        'Trophy Shops',
        'Real Estate Law',
        'Security Services',
        'Rehabilitation Center',
        'Retirement Homes',
        'Life Insurance',
        'Dry Cleaning',
        'Pet Adoption',
        'Home Staging',
        'Gold Buyers',
        'Pawn Shops',
        'Farming Equipment',
        'Orthotics',
        'Criminal Defense Law',
        'DUI Law',
        'Feng Shui',
        'Oncologist',
        'Art Space Rentals',
        'Pet Boarding',
        'Butcher',
        'Prenatal/Perinatal Care',
        'RV Rental',
        'Newspapers & Magazines',
        'Shredding Services',
        'Officiants',
        'Mailbox Centers',
        'General Litigation',
        'Traffic Ticketing Law',
        'Estate Planning Law',
        'Medical Supplies',
        'Vehicle Wraps',
        'Medical Foot Care',
        'Carpenters',
        'Decks & Railing',
        'Patio Coverings',
        'Business Consulting',
        'Piano Services',
        'Rolfing',
        'Animal Shelters',
        'Funeral Services & Cemeteries',
        'Health Retreats',
        'Meditation Centers',
        'Water Stores',
        'Cooking Schools',
        'Recording & Rehearsal Studios',
        'Allergists',
        'Vascular Medicine',
        'Observatories',
        'Obstetricians & Gynecologists',
        'Assisted Living Facilities',
        'Home Health Care',
        'Hospice',
        'Retina Specialists',
        'Auction Houses',
        'Hydrotherapy',
        'Mass Media',
        'Print Media',
        'Ranches',
        'Health Insurance Offices',
        'Hair Loss Centers',
        'Insulation Installation',
        'Car Buyers',
        'Colleges & Universities',
        'Massage Schools',
        'Cosmetology Schools',
        'Home Energy Auditors',
        'Donairs',
        'Bookkeepers',
        'Team Building Activities',
        'Grilling Equipment',
        'Debt Relief Services',
        'Financial Advising',
        'Cremation Services',
        'Driving Schools',
        'Framing',
        'Legal Services',
        'Speech Therapists',
        'Architects',
        'Emergency Rooms',
        'Dental Hygienists',
        'Rugs',
        'Employment Law',
        'Vehicle Shipping',
        'Commercial Truck Dealers',
        'Nurse Practitioner',
        'Dumpster Rental',
        'RV Parks',
        'Montessori Schools',
        'Educational Services',
        'Outdoor Furniture Stores',
        'Kitchen Incubators',
        'Powder Coating',
        'Nanny Services',
        'University Housing',
        'Boudoir Photography',
        'Emergency Pet Hospital',
        'Pet Insurance',
        'Business Law',
        'Television Stations',
        'Cooking Classes',
        'Hypnosis/Hypnotherapy',
        'Water Delivery',
        'Hazardous Waste Disposal',
        'Aquarium Services',
        'Psychics',
        'Mortuary Services',
        'Embassy',
        'Editorial Services',
        'Well Drilling',
        'IV Hydration',
        'Wholesalers',
        'Estate Liquidation',
        'Stucco Services',
        'Prosthetics',
        'Traffic Schools',
        'Skilled Nursing',
        'Home Developers',
        'Horse Boarding',
        'Awnings',
        'Livestock Feed & Supply',
        'Mobile Home Dealers',
        'Cryotherapy',
        'Adult Education',
        'Tutoring Centers',
        'Coffee & Tea Supplies',
        'Laser Tag',
        'Safe Stores',
        'Chimney Sweeps',
        'Boat Dealers',
        'Auto Security',
        'Immigration Law',
        'Car Brokers',
        'Endocrinologists',
        'Speakeasies',
        'Bartending Schools',
        'Religious Schools',
        'Language Schools',
        'Investing',
        'Holiday Decorating Services',
        'Holiday Decorations',
        'Special Education',
        'Duplication Services',
        'Fireplace Services',
        'Pet Photography',
        'Valet Services',
        'Private Investigation',
        'Ticket Sales',
        'Traditional Chinese Medicine',
        'Snow Removal',
        'High Fidelity Audio Equipment',
        'Junkyards',
        'Knife Sharpening',
        'Sex Therapists',
        'Fertility',
        'Placenta Encapsulations',
        'Brewing Supplies',
        'Acne Treatment',
        'Wallpapering',
        'Process Servers',
        'Town Car Service',
        'Civic Center',
        'Challenge Courses',
        'Contract Law',
        'IP & Internet Law',
        'Vacation Rental Agents',
        'Addiction Medicine',
        'Colonics',
        'Fire Departments',
        'Test Preparation',
        'Homeowner Association',
        'Psychologists',
        'Motorsport Vehicle Repairs',
        'Police Departments',
        'Senior Centers',
        'Float Spa',
        'Car Inspectors',
        'Trailer Repair',
        'Personal Care Services',
        'Golf Cart Dealers',
        'Motorsport Vehicle Dealers',
        'Veterans Organizations',
        'Environmental Testing',
        'Aircraft Repairs',
        'Trailer Rental',
        'Fishmonger',
        'Aircraft Dealers',
        'College Counseling',
        'Environmental Abatement',
        'LAN Centers',
        'Demolition Services',
        'Car Share Services',
        'Rest Stops',
        '& Probates',
        'Trusts',
        'Wills',
        'Wildlife Control',
        'Furniture Assembly',
        'Dietitians',
        'Urologists',
        'Medical Transportation',
        'Software Development',
        'Game Truck Rental',
        'Gastroenterologist',
        'Propane',
        'Balloon Services',
        'Prosthodontists',
        'Generator Installation/Repair',
        'Golf Cart Rentals',
        'Restaurant Supplies',
        'Pet Breeders',
        'Behavior Analysts',
        'Health Coach',
        'Donation Center',
        'Dive Shops',
        'Carpet Dyeing',
        'Pet Hospice',
        'House Sitters',
        'Workers Compensation Law',
        'Medical Law',
        'Hepatologists',
        'Courthouses',
        'Concierge Medicine',
        'Excavation Services',
        'Mobile Home Repair',
        'Shoe Shine',
        'Medical Cannabis Referrals',
        'Anesthesiologists',
        'Machine & Tool Rental',
        'Solar Panel Cleaning',
        'Holistic Animal Care',
        'Lawn Services',
        'Structural Engineers',
        'Disc Golf',
        'Pick Your Own Farms',
        'Pumpkin Patches',
        'Astrologers',
        'Psychic Mediums',
        'Scooter Rentals',
        'Duty-Free Shops',
        'Osteopathic Physicians',
        'Business Financing',
        'Disability Law',
        'Habilitative Services',
        'Social Security Law',
        'Radio Stations',
        'Car Auctions',
        'Local Fish Stores',
        'Tenant and Eviction Law',
        'Military Surplus',
        'Self-defense Classes',
        'Pet Cremation Services',
        'Sports Psychologists',
        'Rheumatologists',
        'Bounce House Rentals',
        'Furniture Rental',
        'Music Production Services',
        'Animal Physical Therapy',
        'Pulmonologist',
        'Dance Wear',
        'Parenting Classes',
        'Trailer Dealers',
        'Hot Air Balloons',
        'Pensions',
        'Tax Law',
        'Hearing Aids',
        'Mobility Equipment Sales & Services',
        'Tubing',
        'Translation Services',
        'Pedicabs',
        'Immunodermatologists',
        'Adoption Services',
        'Sandblasting',
        'Mystics',
        'Lice Services',
        '3D Printing',
        'Religious Items',
        'Infectious Disease Specialists',
        'Glass Blowing',
        'Alternative Medicine',
        'Bookbinding',
        'Elder Care Planning',
        'Farm Equipment Repair',
        'Childproofing',
        'Customs Brokers',
        'Food Banks',
        'Trivia Hosts',
        'Indoor Playcentre',
        'Foundation Repair',
        'Backflow Services',
        'Beach Equipment Rentals',
        'Toxicologists',
        'Machine Shops',
        'Emergency Medicine',
        'Halotherapy',
        'Teacher Supplies',
        'Passport & Visa Services',
        'Nursing Schools',
        'Misting System Services',
        'Product Design',
        'Mediators',
        'DIY Auto Shop',
        'Ice Delivery',
        'Private Schools',
        'Public Adjusters',
        'Attraction Farms',
        'Proctologists',
        'Cheese Tasting Classes',
        'Hydroponics',
        'Photography Classes',
        'Bike Repair',
        'Patent Law',
        'Crane Services',
        'Storefront Clinics',
        'Gunsmith',
        'Registry Office',
        'Neurotologists',
        'Digitizing Services',
        'Audio/Visual Equipment Rental',
        'Taxidermy',
        'Phlebologists',
        'Waldorf Schools',
        'Indoor Landscaping',
        'Hybrid Car Repair',
        'Entertainment Law',
        'Osteopaths',
        'Pathologists',
        'Gerontologists',
        'DUI Schools',
        'EV Charging Stations',
        'Nephrologists',
        'Kiosk',
        'Land Surveying',
        'Undersea/Hyperbaric Medicine',
        'Halfway Houses',
        'Homeless Shelters',
        'Neuropathologists',
        'Otologists',
        'Dialysis Clinics',
        'Animal Assisted Therapy',
        'Fuel Docks',
        'Luggage Storage',
        'Interlock Systems',
        'Makerspaces'
    ],
    'Sport stadia & events': [
        'Hiking',
        'Swimming Pools',
        'Karate',
        'Yoga',
        'Martial Arts',
        'Sports Clubs',
        'Professional Sports Teams',
        'Stadiums & Arenas',
        'Trainers',
        'Boxing',
        'Skydiving',
        'Golf',
        'Scuba Diving',
        'Tai Chi',
        'Cardio Classes',
        'Paintball',
        'Soccer',
        'Golf Lessons',
        'Amateur Sports Teams',
        'Mountain Biking',
        'Swimming Lessons/Schools',
        'Tennis',
        'Horseback Riding',
        'Muay Thai',
        'Climbing',
        'Interval Training Gyms',
        'Kickboxing',
        'Diving',
        'Gymnastics',
        'Pilates',
        'Airsoft',
        'Summer Camps',
        'Badminton',
        'Chinese Martial Arts',
        'Fishing',
        'Skating Rinks',
        'Races & Competitions',
        'Race Tracks',
        'Paddleboarding',
        'Rafting/Kayaking',
        'Cycling Classes',
        'Spin Classes',
        'Go Karts',
        'Aerial Fitness',
        'Trampoline Parks',
        'Circuit Training Gyms',
        'Taekwondo',
        'Ski Resorts',
        'Ski Schools',
        'Beach Volleyball',
        'Basketball Courts',
        'Rock Climbing',
        'Ziplining',
        'Skate Parks',
        'Brazilian Jiu-jitsu',
        'Baseball Fields',
        'Batting Cages',
        'Rodeo',
        'Archery',
        'Sailing',
        'Squash',
        'Pole Dancing Classes',
        'Snorkeling',
        'Fencing Clubs',
        'Racing Experience',
        'Cheerleading',
        'Surf Schools',
        'Free Diving',
        'Surfing',
        'Bubble Soccer',
        'Skiing',
        'Flyboarding',
        'Hang Gliding',
        'Sledding'
    ],
    'Transport & mobility': [
        'Public Transportation',
        'Limos',
        'Party Bus Rentals',
        'Bikes',
        'Transportation',
        'Parking',
        'Airlines',
        'Train Stations',
        'Flight Instruction',
        'Airport Shuttles',
        'Airports',
        'Bus Rental',
        'Cable Cars',
        'Aerial Tours',
        'Boat Charters',
        'Bike tours',
        'Metro Stations',
        'Bicycles',
        'Scooter Tours',
        'Bike Parking',
        'Bike Sharing',
        'Bus Tours',
        'Airport Terminals',
        'Buses',
        'Taxis',
        'Private Jet Charter',
        'Boating',
        'Airport Lounges',
        'Trains'
    ]
}
